"""
Mutation testing for the Krawczyk operator unit tests (P2).

A passing test suite is only meaningful if it FAILS when the code under test is
wrong. This runner injects two sign/direction mutations into the Krawczyk
operator inside p2_krawczyk_unit_tests.py and confirms the suite catches each:

  Mutation A (defect direction/sign):  I - Y J   ->  I + Y J
  Mutation B (correction sign):        -Y f      ->  +Y f

For each, it runs the mutated suite as a subprocess, records how many assertions
flip, and requires the suite to FAIL. It also runs the unmutated suite and
requires a clean pass. Writes MUTATION_TEST_REPORT.md next to this file.
"""
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
P2 = HERE / "p2_krawczyk_unit_tests.py"
REPORT = HERE / "MUTATION_TEST_REPORT.md"

MUTATIONS = {
    "A_defect_sign": {
        "desc": "defect  I - Y J  ->  I + Y J   (matrix direction / sign)",
        "old": "                v -= Yb[i][k] * J[k][j]",
        "new": "                v += Yb[i][k] * J[k][j]",
    },
    "B_correction_sign": {
        "desc": "correction  -Y f  ->  +Y f       (residual sign)",
        "old": "            v -= Yb[i][j] * residual[j]",
        "new": "            v += Yb[i][j] * residual[j]",
    },
}


def run(src_path: Path):
    p = subprocess.run([sys.executable, str(src_path)],
                       capture_output=True, text=True)
    out = p.stdout
    passed = "P2 RESULT: PASS" in out
    m = re.search(r"\((\d+)/(\d+) logic assertions\)", out)
    npass, ntot = (int(m.group(1)), int(m.group(2))) if m else (None, None)
    flipped = out.count("[XX]")
    return {"exit": p.returncode, "passed": passed,
            "npass": npass, "ntot": ntot, "flipped": flipped, "stdout": out}


def main():
    base_src = P2.read_text()

    clean = run(P2)
    lines = ["# Mutation Test Report -- Krawczyk operator (P2)", "",
             "Generated by `tests/audit_closure/run_mutation_tests.py`.", "",
             "A unit-test suite is only meaningful if it fails on a wrong "
             "operator. Below, the unmutated suite passes cleanly, and each "
             "single-line sign/direction mutation of the Krawczyk operator is "
             "caught (suite fails).", "",
             "## Unmutated suite", "",
             f"- result: **{'PASS' if clean['passed'] else 'FAIL'}** "
             f"({clean['npass']}/{clean['ntot']} assertions)",
             f"- assertions flipped: {clean['flipped']}", ""]

    all_ok = clean["passed"] and clean["flipped"] == 0
    lines += ["## Injected mutations", "",
              "| id | mutation | suite result | assertions flipped | caught |",
              "|----|----------|--------------|--------------------|--------|"]

    tmp = HERE / "_mutation_tmp.py"
    try:
        for mid, mut in MUTATIONS.items():
            assert mut["old"] in base_src, f"anchor not found for {mid}"
            tmp.write_text(base_src.replace(mut["old"], mut["new"]))
            r = run(tmp)
            caught = (not r["passed"]) and r["exit"] != 0 and r["flipped"] > 0
            all_ok = all_ok and caught
            lines.append(
                f"| {mid} | `{mut['desc']}` | "
                f"{'PASS' if r['passed'] else 'FAIL'} "
                f"({r['npass']}/{r['ntot']}) | {r['flipped']} | "
                f"{'yes' if caught else 'NO'} |")
    finally:
        if tmp.exists():
            tmp.unlink()

    lines += ["", "## Verdict", "",
              f"**{'PASS' if all_ok else 'FAIL'}** -- "
              + ("clean suite green and every mutation caught."
                 if all_ok else "mutation coverage incomplete."), ""]

    REPORT.write_text("\n".join(lines))
    print("\n".join(lines))
    print(f"\nwrote {REPORT}")
    return all_ok


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
